Tesouraria.Apresentacao/ViewModels/TaxaViewModel.cs
namespace Tesouraria.Apresentacao.ViewModels
{
    public class TaxaViewModel
    {
        public int TaxaId { get; set; }
        public string Nome { get; set; }
        public decimal Valor { get; set; }
        public bool Selecionado { get; set; }
    }
}

Tesouraria.Apresentacao/Controllers/TaxaController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using Tesouraria.Apresentacao.ViewModels;
using Tesouraria.Dominio.Entidades;
using Tesouraria.Dominio.Interfaces.Servicos;
using Tesouraria.Dominio.Servicos.InjecaoDependencia;

namespace Tesouraria.Apresentacao.Controllers
{
    public class TaxaController : Controller
    {
        private readonly ITaxaServicos _taxaServicos = ResolvedorDependencias.Resolve<ITaxaServicos>();

        #region Index
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string pesquisa)
        {
            var _taxaVM = Mapper.Map<IList<Taxa>, IList<TaxaViewModel>>(_taxaServicos.ObtemTodos()
                .Where(x =>
                    x.TaxaId.ToString().Contains(pesquisa) ||
                    (x.Nome != null && x.Nome.Contains(pesquisa)) ||
                    (x.Valor != null && x.Valor.ToString().Contains(pesquisa)))
                    .ToList());

            return View(_taxaVM);
        }
        #endregion

        #region Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(TaxaViewModel taxaViewModel)
        {
            if (ModelState.IsValid)
            {
                var _taxa = Mapper.Map<TaxaViewModel, Taxa>(taxaViewModel);
                _taxaServicos.Salva(_taxa);
                return RedirectToAction("Index");
            }

            return View(taxaViewModel);
        }
        #endregion

        #region Edit
        public ActionResult Edit(int taxaId)
        {
            var _taxa = _taxaServicos.ObtemPorId(taxaId);
            var _taxaVM = Mapper.Map<Taxa, TaxaViewModel>(_taxa);

            return View(_taxaVM);
        }

        [HttpPost]
        public ActionResult Edit(TaxaViewModel taxaViewModel)
        {
            if (ModelState.IsValid)
            {
                var _taxa = Mapper.Map<TaxaViewModel, Taxa>(taxaViewModel);
                _taxaServicos.Salva(_taxa);
                return RedirectToAction("Index");
            }

            return View(taxaViewModel);
        }
        #endregion
    }
}

Tesouraria.Apresentacao/Views/Taxa/Create.cshtml
@model Tesouraria.Apresentacao.ViewModels.TaxaViewModel
@{
    ViewBag.Title = "Cadastro de Taxas";
}
@using (Html.BeginForm("Create", "Taxa", FormMethod.Post, new { id = "form" }))
{
    <h2 class="portlet-title">
        <i class="fa fa-usd"></i>&nbsp;Novo Registro
        <button type="button" class="btn btn-primary pull-right" id="btSalvar">
            <span class="fa fa-save"></span>&nbsp;Salvar
        </button>
        <button type="button" class="btn pull-right" style="margin-right: 10px" id="btVoltar">
            <span class="fa fa-arrow-circle-left"></span><span>&nbsp;Voltar</span>
        </button>
    </h2>
    <hr />
    <br />
    <fieldset>
        @Html.Partial("Form", Model)
    </fieldset>
}
<script type="text/javascript" src="~/Scripts/Tesouraria/TaxaScript.js"></script>

Tesouraria.Apresentacao/Views/Taxa/Edit.cshtml
@model Tesouraria.Apresentacao.ViewModels.TaxaViewModel
@{
    ViewBag.Title = "Cadastro de Taxas";
}
@using (Html.BeginForm("Edit", "Taxa", FormMethod.Post, new { id = "form" }))
{
    <h2 class="portlet-title">
        <i class="fa fa-usd"></i>&nbsp;Editar Registro
        <button type="button" class="btn btn-primary pull-right" id="btSalvar">
            <span class="fa fa-save"></span><span>&nbsp;Salvar</span>
        </button>
        <button type="button" class="btn pull-right" style="margin-right: 10px" id="btVoltar">
            <span class="fa fa-arrow-circle-left"></span><span>&nbsp;Voltar</span>
        </button>
    </h2>
    <hr />
    <br />
    <fieldset>
        @Html.Partial("Form", Model)
        @Html.HiddenFor(x => x.TaxaId)
    </fieldset>
}
<script type="text/javascript" src="~/Scripts/Tesouraria/TaxaScript.js"></script>

Tesouraria.Apresentacao/Views/Taxa/Form.cshtml
@model Tesouraria.Apresentacao.ViewModels.TaxaViewModel
<div class="container">
    <form class="form-horizontal" role="form">
    <div class=" col-sm-6">
        <div class="row form-group">
            <div class="col-sm-12">
                @Html.LabelFor(x => x.Nome, new { @class = "control-label" })
            </div>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Nome, new { @class = "form-control" })
            </div>
        </div>
        <div class="row form-group">
            <div class="col-sm-12">
                @Html.LabelFor(x => x.Valor, new { @class = "control-label" })
            </div>
            <div class="col-sm-5">
                @Html.TextBoxFor(x => x.Valor, new { @class = "form-control", id = "txtValor" })
            </div>
        </div>
    </div>
    </form>
</div>

Tesouraria.Apresentacao/Views/Taxa/Index.cshtml
@model IEnumerable<Tesouraria.Apresentacao.ViewModels.TaxaViewModel>
@{
    ViewBag.Title = "Cadastro de Taxas";
}
<h2 class="portlet-title">
    <i class="fa fa-usd">&nbsp;Cadastro de Taxas</i>
    <button type="button" class="btn btn-primary pull-right" id="btNovo">
        <span class="fa fa-file"></span><span>&nbsp; Novo Registro</span>
    </button>
</h2>
<hr />
<br />
@using (Html.BeginForm("Index", "Taxa", FormMethod.Post, new { id = "form" }))
{
    <fieldset>
        <div class="panel" style="background-color: #EEEEEE">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-sm-10">
                        <label>
                            Pesquisa</label>
                        @Html.TextBox("pesquisa", null, new { @class = "form-control input-sm" })
                    </div>
                    <div class="col-sm-1 pull-right">
                        <br />
                        <button type="submit" class="btn btn-primary pull-right" id="btPesquisar">
                            <span class="fa fa-search"></span><span>&nbsp;Buscar</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </fieldset>
}
@if (Model != null)
{
    <div class="container" style="margin-bottom: 50px;">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th class="col-sm-2">
                        Código
                    </th>
                    <th class="col-sm-6">
                        @Html.DisplayNameFor(x => x.Nome)
                    </th>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(x => x.Valor)
                    </th>
                    <th class="col-sm-2 text-center">
                        Editar
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="col-sm-2">
                            @Html.DisplayFor(x => item.TaxaId)
                        </td>
                        <td class="col-sm-6">
                            @Html.DisplayFor(x => item.Nome)
                        </td>
                        <td class="col-sm-2">
                            @Html.DisplayFor(x => item.Valor)
                        </td>
                        <td class="col-sm-2 text-center">
                            <a href="@Url.Action("Edit", "Taxa", new { taxaId = item.TaxaId })" class="btn btn-primary">
                                <i class="fa fa-pencil"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
<script type="text/javascript" src="~/Scripts/Tesouraria/TaxaScript.js"></script>