Tesouraria.Apresentacao/ViewModels/PessoaViewModel.cs
namespace Tesouraria.Apresentacao.ViewModels
{
    public class PessoaViewModel
    {
        public int PessoaId { get; set; }
        public string Nome { get; set; }
        public string Lugar { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
        public bool Selecionado { get; set; }
    }
}

Tesouraria.Apresentacao/Controllers/PessoaController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using Tesouraria.Apresentacao.ViewModels;
using Tesouraria.Dominio.Entidades;
using Tesouraria.Dominio.Interfaces.Servicos;
using Tesouraria.Dominio.Servicos.InjecaoDependencia;

namespace Tesouraria.Apresentacao.Controllers
{
    public class PessoaController : Controller
    {
        private readonly IPessoaServicos _pessoaServicos = ResolvedorDependencias.Resolve<IPessoaServicos>();

        #region Index
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string pesquisa)
        {
            var _pessoaVM = Mapper.Map<IList<Pessoa>, IList<PessoaViewModel>>(_pessoaServicos.ObtemTodos()
                .Where(x =>
                    x.PessoaId.ToString().Contains(pesquisa) ||
                    (x.Nome != null && x.Nome.Contains(pesquisa)) ||
                    (x.Lugar != null && x.Lugar.Contains(pesquisa)) ||
                    (x.Telefone != null && x.Telefone.Contains(pesquisa)))
                    .OrderBy(x => x.Nome)
                    .ToList());

            return View(_pessoaVM);
        }
        #endregion

        #region Create
        public ActionResult Create()
        {
            ViewBag.Lugares = new SelectList(new string[]
            {
                "SELECIONE",
                "NÃO SÓCIO",
                "QUADRO DE SÓCIO", 
                "CORPO INSTRUTIVO", 
                "CORPO DO CONSELHO", 
                "QUADRO DE MESTRE"
            });

            return View();
        }

        [HttpPost]
        public ActionResult Create(PessoaViewModel pessoaViewModel)
        {
            if (ModelState.IsValid)
            {
                var _pessoa = Mapper.Map<PessoaViewModel, Pessoa>(pessoaViewModel);
                _pessoaServicos.Salva(_pessoa);
                return RedirectToAction("Index");
            }

            return View(pessoaViewModel);
        }
        #endregion

        #region Edit
        public ActionResult Edit(int pessoaId)
        {
            ViewBag.Lugares = new SelectList(new string[]
            {
                "SELECIONE",
                "NÃO SÓCIO",
                "QUADRO DE SÓCIO", 
                "CORPO INSTRUTIVO", 
                "CORPO DO CONSELHO", 
                "QUADRO DE MESTRE"
            });

            var _pessoa = _pessoaServicos.ObtemPorId(pessoaId);
            var _pessoaVM = Mapper.Map<Pessoa, PessoaViewModel>(_pessoa);

            return View(_pessoaVM);
        }

        [HttpPost]
        public ActionResult Edit(PessoaViewModel pessoaViewModel)
        {
            if (ModelState.IsValid)
            {
                var _pessoa = Mapper.Map<PessoaViewModel, Pessoa>(pessoaViewModel);
                _pessoaServicos.Salva(_pessoa);
                return RedirectToAction("Index");
            }

            return View(pessoaViewModel);
        }
        #endregion
    }
}

Tesouraria.Apresentacao/Views/Pessoa/Create.cshtml
@model Tesouraria.Apresentacao.ViewModels.PessoaViewModel
@{
    ViewBag.Title = "Cadastro de Pessoas";
}
@using (Html.BeginForm("Create", "Pessoa", FormMethod.Post, new { id = "form" }))
{
    <h2 class="portlet-title">
        <i class="fa fa-users"></i>&nbsp;Novo Registro
        <button type="button" class="btn btn-primary pull-right" id="btSalvar">
            <span class="fa fa-save"></span><span>&nbsp;Salvar</span>
        </button>
        <button type="button" class="btn pull-right" style="margin-right: 10px" id="btVoltar">
            <span class="fa fa-arrow-circle-left"></span><span>&nbsp;Voltar</span>
        </button>
    </h2>
    <hr />
    <br />
    <fieldset>
        @Html.Partial("Form", Model)
    </fieldset>
}
<script type="text/javascript" src="~/Scripts/Tesouraria/PessoaScript.js"></script>

Tesouraria.Apresentacao/Views/Pessoa/Edit.cshtml
@model Tesouraria.Apresentacao.ViewModels.PessoaViewModel
@{
    ViewBag.Title = "Cadastro de Pessoas";
}
@using (Html.BeginForm("Edit", "Pessoa", FormMethod.Post, new { id = "form" }))
{
    <h2 class="portlet-title">
        <i class="fa fa-users"></i>&nbsp;Editar Registro
        <button type="button" class="btn btn-primary pull-right" id="btSalvar">
            <span class="fa fa-save"></span><span>&nbsp;Salvar</span>
        </button>
        <button type="button" class="btn pull-right" style="margin-right: 10px" id="btVoltar">
            <span class="fa fa-arrow-circle-left"></span><span>&nbsp;Voltar</span>
        </button>
    </h2>
    <hr />
    <br />
    <fieldset>
        @Html.Partial("Form", Model)
        @Html.HiddenFor(x => x.PessoaId)
    </fieldset>
}
<script type="text/javascript" src="~/Scripts/Tesouraria/PessoaScript.js"></script>

Tesouraria.Apresentacao/Views/Pessoa/Form.cshtml
@model Tesouraria.Apresentacao.ViewModels.PessoaViewModel
<div class="container">
    <form class="form-horizontal" role="form">
    <div class="col-sm-6">
        <div class="row form-group">
            <div class="col-sm-12">
                @Html.LabelFor(x => x.Nome, new { @class = "control-label" })
            </div>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Nome, new { @class = "form-control" })
            </div>
        </div>
        <div class="row form-group">
            <div class="col-sm-12">
                @Html.LabelFor(x => x.Lugar, new { @class = "control-label" })
            </div>
            <div class="col-sm-10">
                @Html.DropDownListFor(x => x.Lugar, ViewBag.Lugares as SelectList, new { @class = "form-control" })
            </div>
        </div>
        <div class="row form-group">
            <div class="col-sm-12">
                @Html.LabelFor(x => x.Telefone, new { @class = "control-label" })
            </div>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Telefone, new { @class = "form-control" })
            </div>
        </div>
        <div class="row form-group">
            <div class="col-sm-12">
                @Html.LabelFor(x => x.Email, new { @class = "control-label" })
            </div>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
            </div>
        </div>
    </div>
    </form>
</div>

Tesouraria.Apresentacao/Views/Pessoa/Index.cshtml
@model IEnumerable<Tesouraria.Apresentacao.ViewModels.PessoaViewModel>
@{
    ViewBag.Title = "Cadastro de Pessoas";
}
<h2 class="portlet-title">
    <i class="fa fa-users">&nbsp;Cadastro de Pessoas</i>
    <button type="button" class="btn btn-primary pull-right" id="btNovo">
        <span class="fa fa-file"></span><span>&nbsp; Novo Registro</span>
    </button>
</h2>
<hr />
<br />
@using (Html.BeginForm("Index", "Pessoa", FormMethod.Post, new { id = "form" }))
{
    <fieldset>
        <div class="panel" style="background-color: #EEEEEE">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-sm-10">
                        <label>
                            Pesquisa</label>
                        @Html.TextBox("pesquisa", null, new { @class = "form-control input-sm" })
                    </div>
                    <div class="col-sm-1 pull-right">
                        <br />
                        <button type="submit" class="btn btn-primary pull-right" id="btPesquisar">
                            <span class="fa fa-search"></span><span>&nbsp;Buscar</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </fieldset>
}
@if (Model != null)
{
    <div class="container" style="margin-bottom: 50px;">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th class="col-sm-2">
                        Código
                    </th>
                    <th class="col-sm-4">
                        @Html.DisplayNameFor(x => x.Nome)
                    </th>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(x => x.Lugar)
                    </th>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(x => x.Telefone)
                    </th>
                    <th class="col-sm-2 text-center">
                        Editar
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="col-sm-2">
                            @Html.DisplayFor(x => item.PessoaId)
                        </td>
                        <td class="col-sm-4">
                            @Html.DisplayFor(x => item.Nome)
                        </td>
                        <td class="col-sm-2">
                            @Html.DisplayFor(x => item.Lugar)
                        </td>
                        <td class="col-sm-2">
                            @Html.DisplayFor(x => item.Telefone)
                        </td>
                        <td class="col-sm-2 text-center">
                            <a href="@Url.Action("Edit", "Pessoa", new { pessoaId = item.PessoaId })" class="btn btn-primary">
                                <i class="fa fa-pencil"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
<script type="text/javascript" src="~/Scripts/Tesouraria/PessoaScript.js"></script>